server:
  port: 9093
spring:
  application:
    name: boot-cloud-nacos-consumer-feign-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8077
feign:
  sentinel:
    enabled: true
