server:
  port: 9093
spring:
  application:
    name: boot-cloud-nacos-consumer-feign-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  sentinel:
    enabled: true