server:
  port: 8083

spring:
  application:
    name: spring-cloud-consumer-application

# defaultZone让客户端知道去哪里注册服务
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost