spring:
  application:
    name: spring-cloud-square-retrofit-aplication
server:
  port: 9090
# defaultZone让客户端知道去哪里注册服务
eureka:
  client:
    serviceUrl:
      # defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka,http://eureka:8003/eureka
      defaultZone: http://localhost:8000/eureka
    register-with-eureka: true # 将自己注册到eureka服务中
    fetch-registry: true # 不从eureka服务中获取服务列表信息
  instance:
    hostname: spring-cloud-square-retrofit-aplication
    prefer-ip-address: true # 展示ip地址
