# defaultZone让客户端知道去哪里注册服务
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka,http://localhost:8003/eureka
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: spring-cloud-provider-application

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: debug
---
server:
  port: 8081
spring:
  profiles: provider-server1
---
server:
     port: 8082

spring:
  profiles: provider-server2