server:
  port: 8081

spring:
  application:
    name: spring-cloud-provider-application

# defaultZone让客户端知道去哪里注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost