---
spring:
  application:
    name: spring-boot-cloud-eureka-server
  config:
    activate:
      on-profile: eureka1

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2:8002/eureka,http://eureka3:8003/eureka #eureka服务地址
    fetch-registry: false # 不从eureka服务中获取服务列表
    register-with-eureka: false # 不将自己注册到eureka服务中
  instance:
    hostname: eureka1 #示例名称

---
spring:
  application:
    name: spring-boot-cloud-eureka-server
  config:
    activate:
      on-profile: eureka2

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka3:8003/eureka
    fetch-registry: false # 不从eureka服务中获取服务列表
    register-with-eureka: false # 不将自己注册到eureka服务中
  instance:
    hostname: eureka2

---
spring:
  application:
    name: spring-boot-cloud-eureka-server
  config:
    activate:
      on-profile: eureka3

server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka
    fetch-registry: false # 不从eureka服务中获取服务列表
    register-with-eureka: false # 不将自己注册到eureka服务中
  instance:
    hostname: eureka3