server:
  port: 9090
spring:
  application:
    name: boot-cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
service:
  nacos-provider:
    name: boot-cloud-nacos-provider # https://cloud.spring.io/spring-cloud-openfeign/reference/html/
feign:
  okhttp:
    enabled: true # 开启okhttp，参考FeignLoadBalancerAutoConfiguration、OkHttpFeignLoadBalancerConfiguration