server:
  port: 8091

spring:
  application:
    name: spring-cloud-feign-consumer-application


# defaultZone让客户端知道去哪里注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka,http://eureka3:8003/eureka
      # defaultZone: http://localhost:8000/eureka
    fetch-registry: true # 从eureka服务中获取服务列表
    register-with-eureka: false # 不将自己注册到eureka中
  instance:
    hostname: spring-cloud-feign-consumer-application
feign:
  hystrix:
    enabled: true