---
spring:
  application:
    name: spring-boot-cloud-eureka-server
  profiles: eureka1

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2:8002/eureka,http://eureka3:8003/eureka
  instance:
    hostname: eureka1

---
spring:
  application:
    name: spring-boot-cloud-eureka-server
  profiles: eureka2

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka3:8003/eureka
  instance:
    hostname: eureka2

---
spring:
  application:
    name: spring-boot-cloud-eureka-server
  profiles: eureka3

server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka
  instance:
    hostname: eureka3