server:
  port: 9090
spring:
  application:
    name: openfeign-consumer-service
  cloud:
    consul: # consul注册中心相关配置
      host: localhost # consul ip
      port: 8500 # consul 端口
      discovery:
        register: true # 是否注册服务，默认值注册服务
        health-check-path: /actuator/health # 健康检查路径，默认值/actuator/health
        health-check-interval: 10s # 健康检查时间间隔，默认值10s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        # 指定实例id，默认情况下会使用${spring.application.name}-${server.port}格式，假如集群应用名称一致、端口一致、ip不一致，
        # 反注册服务的时候使用${spring.application.name}-${server.port}格式，会对所有服务进行反注册
    loadbalancer:
      cache:
        enabled: false
        # 是否开始缓存，如果开启缓存，服务提供者实例重启，会偶现服务调用失败场景，默认缓存时间35s
        # 参考LoadBalancerCacheAutoConfiguration和LoadBalancerCacheProperties

# feign相关配置
feign:
  okhttp:
    enabled: true # 使用OkHttp作为HttpClient
  client:
    config: # 参考FeignClientProperties中的config
      openfeign-provider-service: # 调用服务名称
        loggerLevel: full # 日志级别，参考：feign.Logger.Level
        connectTimeout: 3000 # 连接超时时间
        readTimeout: 3000 # 读取超时时间
        retryer: com.boot.cloud.openfeign.client.retry.RpcRetryer # 指定重试策略，也可以使用feign.Retryer.Default默认重试策略
        requestInterceptors: # 定义拦截器
          - com.boot.cloud.openfeign.client.interceptor.PrintLogInterceptor
#logging:
#  level:
#    com.boot.cloud: debug

