spring:
  application:
    name: boot-cloud-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8081
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: boot-cloud-nacos-provider1
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: boot-cloud-nacos-provider2
---
server:
  port: 8083
spring:
  config:
    activate:
      on-profile: boot-cloud-nacos-provider3